spring:
  profiles:
    active: loadInitialData
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true


mail:
  from: '76077-99993@fitnestracker.com"'
  host: 'sandbox.smtp.mailtrap.io'
  port: 587
  username: 'example'
  password: 'example'
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
server:
  port: 9090